apiVersion: v1
kind: Event
metadata:
  name: event-11
  namespace: default
reason: "CreateNodredPod"
message: "nodered-7" # POD name or other relevant info
involvedObject:
  kind: NodeRedKop
  name: nodered-setup
  namespace: default
  apiVersion: webapp.myoperator/v1
type: Normal
source:
  component: "manual-trigger"